kind: Deployment
apiVersion: apps/v1
metadata:
  name: hello-world
spec:
  replicas: 1
  selector: 
    matchLabels: 
      app: hello-world
  template:
    metadata:
      name: hello-world
      labels:
        app: hello-world
    spec:
      containers:
        - name: hello-world
          image: lalienagabriel/hello-world:main
          ports:
          - containerPort: 8080
          imagePullPolicy: Always
